import React, { Component } from 'react'
import Navbar from '../../../Navbars/darkNavbar'
import aboutUsImage from '../../../../Assets/aboutus.png'
import Footer from '../../../Footer'
import instaBlack from '../../../../Assets/insta-black.png'
import fbBlack from '../../../../Assets/fb-black.png'
import twitterBlack from '../../../../Assets/twitter-black.png'
import '../Stylesheets/TandC.scss'

class AboutUs extends Component {
    render() {

        return (
            <div style={{ fontFamily: 'Raleway' }} >
                <Navbar history = {this.props.history} />
                <div style={{ display: 'flex', margin: '3rem' }} className="TandC-head-div" >
                    <div style={{ flex: 1, letterSpacing: 2.4, fontSize: '2rem' }} >
                        <div style={{ fontFamily: 'Crimson Text' }} className="TandC-heading"  >
                            TERMS & CONDITIONS
                        </div>
                        <div style={{ marginTop: '2rem', letterSpacing: 1.27, fontSize: '1.1rem' }} >
                            We, BetaHouse LLP, are a limited liability partnership firm incorporated under the legal provisions of the Limited Liability partnership act, 2008 and having its registered office at “K18 Anna Nagar East, Chennai-600102” represented by its Directors/ Partners hereinafter referred to as the “Firm” (where such expression shall, unless repugnant to the context thereof, be deemed to include its respective legal heirs, representatives, administrators, permitted successors and assigns) are operating this Website on the brand name “Beta House”.
                            This legal agreement is an electronic record in terms of Indian Information Technology Act, 2000 and rules there under as applicable and the amended provisions about electronic records in various statutes as amended by the Indian Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                            This legal document is published following the provisions of Rule 3 (1) of the Indian Information Technology (Intermediaries guidelines) Rules, 2011 and Rule 4 of the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011 of Information Technology Act, 2000 amended through Information Technology Amendment Act, 2008 that require publishing the Terms of Services and practices for access or usage of “www.betahouse.co.in” (“website/platform”)
                        </div>
                        <div style={{ marginTop: '3rem' }} className="TandC-images"  >
                            <a href="#"><img src={twitterBlack} style={{ marginRight: '1.1rem' }} width="4%" /></a>
                            <a href="#"><img src={instaBlack} style={{ marginRight: '.8rem' }} width="4%" /></a>
                            <a href="#"> <img src={fbBlack} width="1.8%" /> </a>
                        </div>
                        <div style={{ fontSize: '1rem', letterSpacing: 1.2, marginTop: '0.5rem' }} >
                            For anything else, mail us at help@betahouse.co.in
                        </div>
                    </div>
                    <div style={{ flex: 1, display: 'flex', justifyContent: 'center', alignItems: 'center' }} >
                        <img src={aboutUsImage} className="TandC-main-image" />
                    </div>
                </div>
                <Footer />
            </div>
        )
    }
}

export default AboutUs
